### ISSUE TITLE
Prepare for publication in JOSS

### ISSUE THREAD

**Issue by BenjMy** [Peruz/icsd#3]
The ICSD code is increasingly used in the literature and [requested](https://gitlab.com/hkex/resipy/-/issues/354) and yet not published. We should consider sooner or later releasing an accessible version on conda and pip and publish the code tentatively into [JOSS](https://joss.theoj.org/).

- [x] [OSI-approved license](https://opensource.org/licenses)
- [x] improve documentation (particulary pusblish the code API)
- [x] add tests
- [x] write paper.md

**Comment by Peruz** [comment]
Hi Ben, thanks for pushing this forward. I think JOSS has some requirements, for example the lines of codes and commits.
See here https://joss.readthedocs.io/en/latest/submitting.html
We only have 4 commits (they ask 100) but this may not be a problem if they understand that this repository was created to combine our separate repositories. What do you think?

Are you currently working on any of the points you highlighted?

Best

**Comment by BenjMy** [comment]
Hi Luca, 

Yes I know about the requirements, and yes we'd need to argue that we merged our repositories. 
I'll be working in my spare time.
Already added the LICENCE if you want to review it (https://github.com/Peruz/icsd/pull/4) 

Cheers,

**Comment by BenjMy** [comment]
Can you set the default branch to main instead of master? 
See here for instructions: https://www.git-tower.com/learn/git/faq/git-rename-master-to-main
Thx.

**Comment by Peruz** [comment]
_main_ should now be the default branch, and _master_ was deleted. Let me know if this looks solved on your side too.
Cheers!
